/**
 * Maps country names (as stored in the Country lookup collection) to
 * their international dial codes.  Keys are case-sensitive and should
 * match exactly what the master admin enters in the Country lookup.
 *
 * Usage:  DIAL_CODES['Tunisia'] → '+216'
 */
const DIAL_CODES = {
  // Africa
  Algeria:                  '+213',
  Angola:                   '+244',
  Benin:                    '+229',
  Botswana:                 '+267',
  'Burkina Faso':           '+226',
  Burundi:                  '+257',
  'Cabo Verde':             '+238',
  Cameroon:                 '+237',
  'Central African Republic': '+236',
  Chad:                     '+235',
  Comoros:                  '+269',
  Congo:                    '+242',
  'Democratic Republic of the Congo': '+243',
  Djibouti:                 '+253',
  Egypt:                    '+20',
  'Equatorial Guinea':      '+240',
  Eritrea:                  '+291',
  Eswatini:                 '+268',
  Ethiopia:                 '+251',
  Gabon:                    '+241',
  Gambia:                   '+220',
  Ghana:                    '+233',
  Guinea:                   '+224',
  'Guinea-Bissau':          '+245',
  'Ivory Coast':            '+225',
  Kenya:                    '+254',
  Lesotho:                  '+266',
  Liberia:                  '+231',
  Libya:                    '+218',
  Madagascar:               '+261',
  Malawi:                   '+265',
  Mali:                     '+223',
  Mauritania:               '+222',
  Mauritius:                '+230',
  Morocco:                  '+212',
  Mozambique:               '+258',
  Namibia:                  '+264',
  Niger:                    '+227',
  Nigeria:                  '+234',
  Rwanda:                   '+250',
  'São Tomé and Príncipe':  '+239',
  Senegal:                  '+221',
  Seychelles:               '+248',
  'Sierra Leone':           '+232',
  Somalia:                  '+252',
  'South Africa':           '+27',
  'South Sudan':            '+211',
  Sudan:                    '+249',
  Tanzania:                 '+255',
  Togo:                     '+228',
  Tunisia:                  '+216',
  Uganda:                   '+256',
  Zambia:                   '+260',
  Zimbabwe:                 '+263',

  // Americas
  'Antigua and Barbuda':    '+1',
  Argentina:                '+54',
  Bahamas:                  '+1',
  Barbados:                 '+1',
  Belize:                   '+501',
  Bolivia:                  '+591',
  Brazil:                   '+55',
  Canada:                   '+1',
  Chile:                    '+56',
  Colombia:                 '+57',
  'Costa Rica':             '+506',
  Cuba:                     '+53',
  Dominica:                 '+1',
  'Dominican Republic':     '+1',
  Ecuador:                  '+593',
  'El Salvador':            '+503',
  Grenada:                  '+1',
  Guatemala:                '+502',
  Guyana:                   '+592',
  Haiti:                    '+509',
  Honduras:                 '+504',
  Jamaica:                  '+1',
  Mexico:                   '+52',
  Nicaragua:                '+505',
  Panama:                   '+507',
  Paraguay:                 '+595',
  Peru:                     '+51',
  'Saint Kitts and Nevis':  '+1',
  'Saint Lucia':            '+1',
  'Saint Vincent and the Grenadines': '+1',
  Suriname:                 '+597',
  'Trinidad and Tobago':    '+1',
  'United States':          '+1',
  Uruguay:                  '+598',
  Venezuela:                '+58',

  // Asia
  Afghanistan:              '+93',
  Armenia:                  '+374',
  Azerbaijan:               '+994',
  Bahrain:                  '+973',
  Bangladesh:               '+880',
  Bhutan:                   '+975',
  Brunei:                   '+673',
  Cambodia:                 '+855',
  China:                    '+86',
  Cyprus:                   '+357',
  Georgia:                  '+995',
  India:                    '+91',
  Indonesia:                '+62',
  Iran:                     '+98',
  Iraq:                     '+964',
  Israel:                   '+972',
  Japan:                    '+81',
  Jordan:                   '+962',
  Kazakhstan:               '+7',
  Kuwait:                   '+965',
  Kyrgyzstan:               '+996',
  Laos:                     '+856',
  Lebanon:                  '+961',
  Malaysia:                 '+60',
  Maldives:                 '+960',
  Mongolia:                 '+976',
  Myanmar:                  '+95',
  Nepal:                    '+977',
  'North Korea':            '+850',
  Oman:                     '+968',
  Pakistan:                 '+92',
  Palestine:                '+970',
  Philippines:              '+63',
  Qatar:                    '+974',
  'Saudi Arabia':           '+966',
  Singapore:                '+65',
  'South Korea':            '+82',
  'Sri Lanka':              '+94',
  Syria:                    '+963',
  Taiwan:                   '+886',
  Tajikistan:               '+992',
  Thailand:                 '+66',
  'Timor-Leste':            '+670',
  Turkey:                   '+90',
  Turkmenistan:             '+993',
  'United Arab Emirates':   '+971',
  Uzbekistan:               '+998',
  Vietnam:                  '+84',
  Yemen:                    '+967',

  // Europe
  Albania:                  '+355',
  Andorra:                  '+376',
  Austria:                  '+43',
  Belarus:                  '+375',
  Belgium:                  '+32',
  'Bosnia and Herzegovina': '+387',
  Bulgaria:                 '+359',
  Croatia:                  '+385',
  'Czech Republic':         '+420',
  Denmark:                  '+45',
  Estonia:                  '+372',
  Finland:                  '+358',
  France:                   '+33',
  Germany:                  '+49',
  Greece:                   '+30',
  Hungary:                  '+36',
  Iceland:                  '+354',
  Ireland:                  '+353',
  Italy:                    '+39',
  Kosovo:                   '+383',
  Latvia:                   '+371',
  Liechtenstein:            '+423',
  Lithuania:                '+370',
  Luxembourg:               '+352',
  Malta:                    '+356',
  Moldova:                  '+373',
  Monaco:                   '+377',
  Montenegro:               '+382',
  Netherlands:              '+31',
  'North Macedonia':        '+389',
  Norway:                   '+47',
  Poland:                   '+48',
  Portugal:                 '+351',
  Romania:                  '+40',
  Russia:                   '+7',
  'San Marino':             '+378',
  Serbia:                   '+381',
  Slovakia:                 '+421',
  Slovenia:                 '+386',
  Spain:                    '+34',
  Sweden:                   '+46',
  Switzerland:              '+41',
  Ukraine:                  '+380',
  'United Kingdom':         '+44',
  Vatican:                  '+379',

  // Oceania
  Australia:                '+61',
  Fiji:                     '+679',
  Kiribati:                 '+686',
  'Marshall Islands':       '+692',
  Micronesia:               '+691',
  Nauru:                    '+674',
  'New Zealand':            '+64',
  Palau:                    '+680',
  'Papua New Guinea':       '+675',
  Samoa:                    '+685',
  'Solomon Islands':        '+677',
  Tonga:                    '+676',
  Tuvalu:                   '+688',
  Vanuatu:                  '+678',
};

export default DIAL_CODES;
